FROM alpine:latest

ADD nginx-bin.tar.gz /

VOLUME ["/var/log/nginx", "/var/www"]

RUN apk --update add pcre \
    && addgroup -S nginx \
	&& adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx nginx \
	&& chown -R nginx:nginx /var/log/nginx

CMD nginx
